name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gh-pages.yml
      - public/**
      - src/**
      - index.html

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: build
        run: bun run build
        env:
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/"

      - name: setup pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
